volumes:
  app:
  postgres:

services:
  app:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    tty: true

  postgres:
    container_name: postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Dedroud33
      PGDATA: nuthouse
    volumes:
      - postgres:/data/postgres
      - ./sql_init:/docker-entrypoint-initdb.d/:ro
    env_file:
      - src/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    restart: unless-stopped

