volumes:
  app:

services:
  app:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: uvicorn main:app --reload --port 80 --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 80
    restart: always
    tty: true

