volumes:
  app:
  postgres:

services:
  app:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: uvicorn main:app --reload --port 80 --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 80
    restart: always
    tty: true

    postgres:
      container_name: postgres
      image: "postgres:12"
      environment:
        POSTGRES_USER: ${IMAGE_NAME}
        POSTGRES_PASSWORD: ${IMAGE_NAME}
        PGDATA: ${IMAGE_NAME}
      volumes:
        - postgres:/data/postgres
        - ./sql_init:/docker-entrypoint-initdb.d/:ro
      env_file:
        - ./.env
      ports:
        - "5432:5432"
      healthcheck:
        test: /usr/bin/pg_isready
        interval: 5s
        timeout: 10s
        retries: 120
      restart: unless-stopped

